package nl.mwensveen.adventofcode.year_2024.day_08;

import com.google.common.collect.Multimap;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AntennaParserTest {
    private String input = """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
                    """;

    @Test
    public void testParse() {
        AntennaParser antennaParser = new AntennaParser();
        Multimap<String, Position> grid = antennaParser.parse(input.lines().toList());
        assertTrue(grid.get("0").contains(new Position(1, 8)));
        assertTrue(grid.get("0").contains(new Position(2, 5)));
        assertTrue(grid.get("A").contains(new Position(8, 8)));
        assertEquals(7, grid.size());
    }

}
