package nl.mwensveen.adventofcode.year_2025.day_07;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class TachyonBeamQuantumMoverTest {
    private String input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
                    """;

    @Test
    public void moveDown() {
        var tmp = new TachyonManifoldParser();
        var manifold = tmp.parse(input.lines().toList());
        var start = tmp.findStart(manifold);

        var mover = new TachyonBeamQuantumMover();
        var result = mover.moveDown(manifold, start);

        assertEquals(40, result.intValue());
    }

}
